"""create association object for order_product

Revision ID: 23f0b1a38f76
Revises: 5fcbd5eb2d31
Create Date: 2023-02-09 07:57:52.734709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f0b1a38f76'
down_revision = '5fcbd5eb2d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
