"""add password hashing for users

Revision ID: 5fcbd5eb2d31
Revises: 5f82b379fab4
Create Date: 2023-02-05 12:33:16.163762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcbd5eb2d31'
down_revision = '5f82b379fab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
