"""alter users schema to store postal codes as strings

Revision ID: 991298046294
Revises: 30aebabcbd0c
Create Date: 2023-02-15 22:27:19.444622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991298046294'
down_revision = '30aebabcbd0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=False)

    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('postal_code',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
