"""add store_description for sellers

Revision ID: 9d9e768d87c6
Revises: b56962de9cd9
Create Date: 2023-01-28 08:32:10.083719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9e768d87c6'
down_revision = 'b56962de9cd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_column('store_description')

    # ### end Alembic commands ###
